src/io/file.h: fix build on gcc-12
gcc-12 enables c++17 by default and disallows std::string to be
initialized by NULL pointer:

    src/io/file.h:29:63: error: use of deleted function
      'std::__cxx11::basic_string<...>::basic_string(std::nullptr_t) [...]'
       29 | SPDocument* ink_file_new(const std::string &Template = nullptr);
          |                                                               ^

As C++ does not define behaviour for std::string(NULL) let's use
safe "" as empty value;